trigger:
- main

pool:
  name: ravi123  # Specify the pool name
  demands:
    - agent.name -equals ravi18  # Specify the agent name

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
